name: prob_ranked
scale: 1
pos_offset: 17
add_to_env_rew: false # True to add the environment rewards to the sequence matching rewards 
rank_weighting: .1
post_processing_method: 
    - penalize_inversions