

defaults:
  - reward_model: joint_wasserstein
  - _self_

hydra:
  searchpath:
    - file://../../configs
  run:
    dir: ./eval_logs/${now:%Y-%m-%d-%H%M%S}_rm=${reward_model.name}_src=${eval_data.name}

