skip_gifs: 10

defaults:
  - reward_model: joint_wasserstein
  - joint_eval_data: both_arms_out 
  - _self_

hydra:
  searchpath:
    - file://../../configs
  run:
    dir: ./joint_eval_logs/${now:%Y-%m-%d-%H%M%S}_rm=${reward_model.name}_src=${joint_eval_data.name}

