name: sam2_patch_wasserstein
vlm_model: sam2  # The VLM used to embed a the image
sam2_cfg_path: sam2_hiera_l.yaml
sam2_model_id : facebook/sam2-hiera-large
pos_image_path: 
  - /share/portal/wph52/CrossQ/create_demo/demos/both-arms-out.png
filter_rewards: False
add_to_gt_rewards: True
scale: 1 # Scale the reward before it's added to the ground-truth reward
human_seg_model_path: '/share/portal/hw575/language_irl/pretrained_checkpoints/SGHM-ResNet50.pth'
source_mask_thresh: 0.001
target_mask_thresh: 0.001


### USELESS FOR Sam2
cost_fn: cosine # Options: euclidean, cosine. What function to use to build the cost matrix
reward_batch_size: 16  # Batch size sent to the VLM reward model
image_size: 224  # How should the image be resized
return_ot_plan: False  # (For debugging purpose) Whether to return the OT plan (so that we can visualize)
neg_image_path: []
rank0_batch_size_pct: 0.0  # Determine how many percentage of the batch the main worker (rank = 0) need to process when doing reward calculation
