name: soft_dtw
cost_fn: euclidean_arms_only
gamma: 5
scale: 1
# This does not exist by default
#  You can specify this in the command line: 
#    +seq_reward_model.post_processing_method=stage_reward_based_on_last_state
seq_name: null
reward_vmin: 0
reward_vmax: 2