image_metric: 'wasserstein'
human_seg_model_path: '/share/portal/hw575/language_irl/pretrained_checkpoints/SGHM-ResNet50.pth'
pos_image_path: 
  - axis_exp/humanoid_kneeling_ref.png
source_mask_thresh: 0.001
target_mask_thresh: 0.001