image_metric: 'wasserstein'
human_seg_model_path: '/share/portal/hw575/language_irl/pretrained_checkpoints/SGHM-ResNet50.pth'
ref_image_path: 
  - /share/portal/hw575/CrossQ/sbx/vlm_reward/reward_models/language_irl/preference_data/humans_selected_images/standing_up/anne_standing_front_final-0.png