image_metric: 'wasserstein'
image_size: 448
return_ot_plan: True
human_seg_model_path: '/share/portal/hw575/language_irl/pretrained_checkpoints/SGHM-ResNet50.pth'
pos_image_path: 
  - sbx/vlm_reward/reward_models/language_irl/preference_data/humans_selected_images/kneeling/anne_kneeling_front_final.png
source_mask_thresh: 0.001
target_mask_thresh: .5