seed: 9

n_rollouts: 1  # Number of rollouts/videos to generate

video_base_name: 'standing_up'  # "Name of the video when we just generate one video

model_base_path: null  # Folder to load the model from
model_checkpoint: null  # Model checkpoint zip file name (without .zip) to load

defaults:
  - env: HumanoidSpawnedUpCustom
  - reward_model: hand_engineered
  - rl_algo: crossq
  - _self_

hydra:
  run:
    dir: ./inference_logs/${now:%Y-%m-%d-%H%M%S}_${rl_algo.name}_envr=${env.reward_type}_rm=${reward_model.name}_s=${seed}

# If you want to specify a specific reward function used in the env, you can uncomment and overwrite reward_type
# env:
#   reward_type: both_arms_out_goal_only_euclidean

# If you are using patch wasserstein as reward, you can uncomment and overwrite pos_image_path, neg_image_path in the patch_wasserstein.yaml
# reward_model:
#   pos_image_path:
#     - axis_exp/humanoid_kneeling_ref.png
