seed: 9

n_rollouts: 1  # Number of rollouts/videos to generate

video_base_name: 'arms_out'  # "Name of the video when we just generate one video

model_base_path: train_logs/before_migration_to_hydra/crossq_HumanoidSpawnedUpCustom_r=both_arms_out_goal_only_euclidean_s=9_2024-07-31_22-39-23__ec25b98b/checkpoint  # Folder to load the model from
model_checkpoint: final_model  # Model checkpoint zip file name (without .zip) to load

run_notes: null

defaults:
  - env: HumanoidSpawnedUpCustom
  - reward_model: hand_engineered
  - rl_algo: sb3_sac
  - _self_

hydra:
  run:
    dir: ./inference_logs/${now:%Y-%m-%d-%H%M%S}_${rl_algo.name}_envr=${env.reward_type}_rm=${reward_model.name}_s=${seed}_nt=${run_notes}

# If you want to specify a specific reward function used in the env, you can uncomment and overwrite reward_type
# env:
#   reward_type: both_arms_out_goal_only_euclidean

# If you are using patch wasserstein as reward, you can uncomment and overwrite pos_image_path, neg_image_path in the dino_patch_wasserstein.yaml
# reward_model:
#   pos_image_path:
#     - axis_exp/humanoid_kneeling_ref.png
