target_prompts: # Description of the goal state
  - a humanoid robot practicing gymnastics, doing the side splits
baseline_prompts: # Description of the environment
  - a humanoid robot
alpha: 0 # Alpha value of Baseline CLIP (CO-RELATE)
cache_dir: /home/aw588/git_annshin/CrossQ/cache
