seed: 9

run_notes: null

model_base_path: null  # Folder to load the model from
model_checkpoint: null  # Model checkpoint zip file name (without .zip) to load

compute:
  n_gpu_workers: 1
  n_cpu_workers: 8  # One gym env per cpu

logging:
  log_freq: 300  # How many times to log during training
  video_save_freq: 5000 # Frequency to save the video
  model_save_freq: 50000  # Frequency to save the model

  wandb_project: seq_matching_toy
  wandb_mode: online
  wandb_tags: []

  run_name: null
  run_path: null

env:
  example_name: nav_3by3_0
  episode_length: 10

rl_algo:
  name: ppo
  total_timesteps: 100000
  n_epochs: 10
  lr: 2.5e-4
  batch_size: 64
  gamma: 0.99
  ent_coef: 0.0
  vf_coef: 0.5
  # Used by REINFORCE/Policy Gradient
  n: null
  use_relative_rewards: false

sweep:
  enabled: false
  n_trails: 5

cost_fn: nav_shortest_path

log_folder: seq_matching_toy/rl_train_logs

defaults:
  - seq_reward_model: dtw
  - _self_

hydra:
  run:
    dir: ${log_folder}/${now:%Y-%m-%d-%H%M%S}_map=${env.example_name}_rm=${seq_reward_model.name}_rl=${rl_algo.name}-epochs=${rl_algo.n_epochs}-eplen=${env.episode_length}_s=${seed}_nt=${run_notes}
